# Generated by Django 4.1 on 2022-09-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
    ]
